### ISSUE TITLE
add contract upgradeability

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/parsec-contracts#66]
we want to be able to upgrade the contract with protocol changes of the Plasma chain. But the community should have the ability to veto each upgrade. Process envisioned like this:
1. new contract code is deployed and registered for upgrade.
2. timer runs down over x days.
3. if no majority of token holders veto'ed the upgrade, new contract code is enabled.

**Comment by eshavkun** [comment]
Contracts are now upgradable with ZeppelinOS
New branch pushed: https://github.com/leapdao/leap-contracts/tree/UpgradableContracts

### Summary of changes ###
* Contracts are now Initializable (see /contracts/Initializable.sol)
* Constructors changed to initializers
* Initial values for variables are moved into initializers
* Imports changed from 'openzeppelin-solidity' to 'openzeppelin-eth'
* zos.json created with LeapBridge and ExitToken added
* Basic test: deployed on local (ganache) network and called functions from truffle console

### TODO ###

- [ ] Update test suite
- [ ] Add mock contracts to zos.json - **TBD**
- [ ] Link to openzeppelin-eth as EVM package - **TBD**
- [ ] Check if libraries and Interfaces - **TBD**

### Deployment ###
1. Precondition: ZeppelinOS is globally installed (`npm install --global zos`)
1. `zos push --network NETWORK_NAME`
1. `zos create CONTRACT_NAME --network NETWORK_NAME --init --args "CONSTRUCTOR_PARAMETERS"`

### Important Notes ###
* Constructors are not working with ZeppelinOS. Initializers (`function initialize() initializer public`) are used instead. Initializers are never called automatically (e.g. on contract creation).
* Deployer of the contract becomes its admin. Admin can only call proxy functions (e.g. update contract) but not logic functions. Therefore logic functions must be called from other (non-admin) account

**Comment by eshavkun** [comment]
Regardsing contract upgradability governance:
https://blog.zeppelinos.org/exploring-upgradeability-governance-in-zeppelinos-with-a-gnosis-multisig/
